# Generated by Django 5.1.7 on 2025-03-31 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_cart_user_alter_cart_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Dish Name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price (USD)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/', verbose_name='Dish Image')),
                ('available', models.BooleanField(default=True, verbose_name='Available')),
                ('category', models.CharField(choices=[('Starters', 'Starters'), ('Main Course', 'Main Course'), ('Drinks', 'Drinks'), ('Desserts', 'Desserts')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='dish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.menuitem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='dish',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.menuitem'),
        ),
        migrations.DeleteModel(
            name='Dish',
        ),
    ]
